name: Deploy client to Personal Virtual Server
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Build project 🔧
        run: npm ci && npm run build
        env:
          REACT_APP_GIPHY_API_KEY: ${{ secrets.REACT_APP_GIPHY_API_KEY }}
          REACT_APP_DEPLOY_NETWORK_RPC_URL: ${{ secrets.REACT_APP_DEPLOY_NETWORK_RPC_URL }}
          REACT_APP_DEPLOY_NETWORK_ID: ${{ secrets.REACT_APP_DEPLOY_NETWORK_ID }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - name: Add to known_hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to the server 📦
        run: rsync -avz --delete --no-perms --no-owner --no-group --omit-dir-times ./build/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
